export const QUERYKEYS = {
  GETCATEGORY: "GETCATEGORY",
  GETSINGLEPRODUCT: "GETSINGLEPRODUCT",
  GETCOUPON: "GETCOUPON",
  GETIDFROMEMAIL: "GETIDFROMEMAIL",
  GETSINGLECATEGORY: "GETSINGLECATEGORY",
  GETFROMSEARCH: "GETFROMSEARCH",
  GETUSERIP: "GETUSERIP",
};
